import { Theme } from '@radix-ui/themes';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { AvatarModal } from '@/app/(home)/_components/AvatarModal';
import { CurrentAvatarProvider } from '@/app/(home)/_components/CurrentAvatarContext';

import '@radix-ui/themes/styles.css';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seeds = [
    'monkey1',
    'monkey2',
    'monkey3',
    'monkey4',
    'monkey5',
    'monkey6',
    'monkey7',
    'monkey8',
    'monkey9',
    'monkey10',
    'human1',
    'human2',
  ];

  const assignedSeed = 'monkey1';

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Theme
          accentColor="crimson"
          grayColor="sand"
          radius="large"
          scaling="95%"
        >
          <CurrentAvatarProvider initialSeed={assignedSeed}>
            {children}

            <AvatarModal seeds={seeds} />
          </CurrentAvatarProvider>
        </Theme>
      </body>
    </html>
  );
}
